language: php
php:
  - 7.2
  - 7.3

install:
  - composer require php-coveralls/php-coveralls

before_script:
  - mkdir -p build/logs

after_success:
  - php vendor/bin/php-coveralls -v

cache:
  directories:
    - vendor
